# Generated by Django 4.2.13 on 2024-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('see_list_of_clients', 'Просмотр списка пользователей сервиса'), ('ban_clients', 'Блокирование пользователей сервиса')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'permissions': [('change_mailing_message', 'Изменение сообщения')], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('see_any_mailing_settings', 'Просмотр любых рассылок'), ('switch_of_mailing_settings', 'Отключение рассылки'), ('change_mailing_settings', 'Редактирование рассылки'), ('manage_list_of_mailing_settings', 'Управление списком рассылки')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылок'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Блокирован'),
        ),
    ]
