# Generated by Django 4.2.13 on 2024-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_options_alter_mailingmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='ДД.ММ.ГГГГ 00:00', null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(help_text='ДД.ММ.ГГГГ 00:00', verbose_name='Время запуска'),
        ),
    ]
